// Generated by CoffeeScript 1.6.2
(function() {
  var _this = this;

  $(document).ready(function() {});

  $('form').on('submit', function(event) {
    var searchInput, toSubmit;

    event.preventDefault();
    toSubmit = $(_this);
    searchInput = $('#searchbox').val();
    console.log(searchInput);
    return $.ajax({
      url: 'http://www.omdbapi.com/?s=' + searchInput,
      method: 'get',
      dataType: 'jsonp',
      success: function(searchResult) {
        var movieArray, num, titleList, _i, _len, _results;

        movieArray = searchResult["Search"];
        titleList = $('#movielist');
        _results = [];
        for (_i = 0, _len = movieArray.length; _i < _len; _i++) {
          num = movieArray[_i];
          _results.push($.ajax({
            url: 'http://www.omdbapi.com/?i=' + searchResult["Search"][_i]["imdbID"],
            method: 'get',
            dataType: 'json',
            success: function(movie) {
              var plot, poster, released, titleLink;

              console.log('indivMovie:', movie);
              plot = movie["Plot"];
              released = movie["Released"];
              poster = movie["Poster"];
              titleLink = $('<li><div class="container"><div id="movieposter"><img src=' + poster + '/></div>' + '<div id="movie">' + movie["Title"] + '</div><div id="movieplot"><div id="releasedate">' + released + '</div>' + plot + '</div></div></li>');
              return titleLink.appendTo(titleList);
            }
          }));
        }
        return _results;
      }
    });
  });

}).call(this);
